title: Subham Bansal
logo: /assets/img/dp.png
description: A skilled professional with 8 years of experience in MLops (Machine Learning Operations)and SDET (Software Development Engineer in Test) roles. With a strong background in software Deployments and a deep understanding of machine learning workflows,successfully contributed to the development and deployment of robust, scalable, and efficient products. Developed E2E Automation CI
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
